name: Temporary Windows Environment Session

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  windows_session:
    name: Start Temporary Windows Session (Max 6 hours)
    runs-on: windows-latest # Use a Windows Server runner provided by GitHub

    # Set the maximum timeout for the job in minutes (6 hours = 360 minutes)
    # Note: Free accounts might have shorter limits, but 360 is typical for public repos/paid plans.
    timeout-minutes: 360

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup Environment (Customize as needed)
      run: |
        echo "Setting up the environment..."
        # Add commands here to install software you need using Chocolatey (choco)
        # For example:
        # choco install --no-progress -y nodejs-lts dotnet-sdk git python
        # choco install --no-progress -y googlechrome visualstudiocode
        #
        # Or use setup actions:
        # - name: Setup .NET
        #   uses: actions/setup-dotnet@v3
        #   with:
        #     dotnet-version: '6.0.x'
        #
        # - name: Setup Java
        #   uses: actions/setup-java@v3
        #   with:
        #     distribution: 'temurin'
        #     java-version: '17'

        echo "Environment setup complete (or skipped if no commands added)."
        echo "Starting tmate session for interactive access..."
      shell: pwsh # Use PowerShell

    - name: Setup tmate session for Debugging / Interaction
      # This action creates an SSH or Web Shell connection into the runner.
      # Connection details will be printed in the workflow logs.
      # The job will remain active as long as the tmate session is open or until timeout.
      uses: mxschmitt/action-tmate@v3
      # You can add timeout for the tmate step itself if needed,
      # but the job timeout (360 mins) is the ultimate limit.
      # timeout-minutes: 355 # Example: Give 5 mins buffer before job timeout
      with:
        # Optional: limit access, e.g., install sudo if needed by tmate
        # sudo: true # May require specific runner configurations or permissions

    # The workflow will pause here at the tmate step.
    # It will only proceed (and finish) if the tmate session is exited
    # or if the job's 6-hour timeout is reached.

    - name: Session Ended
      if: always() # Always run this step, even if tmate timed out or failed
      run: |
        echo "tmate session ended or job timed out."
