name: Temporary Windows Environment Session

# Trigger manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  windows_session:
    # Job name in the UI
    name: Start Temporary Windows Session (Max 6 hours)
    # Runner environment
    runs-on: windows-latest

    # Maximum job duration in minutes (GitHub's typical limit for public/paid plans)
    timeout-minutes: 360

    # Sequence of tasks to perform
    steps:
      # Step 1: Get the repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Optional environment setup (customize here)
      - name: Setup Environment (Customize as needed)
        # Use PowerShell on Windows runners
        shell: pwsh
        run: |
          echo "Setting up the environment..."
          # --- ADD YOUR SETUP COMMANDS HERE ---
          # Example using Chocolatey (package manager for Windows):
          # choco install --no-progress -y nodejs-lts git python maven
          #
          # Example using setup actions:
          # - name: Setup .NET SDK
          #   uses: actions/setup-dotnet@v3
          #   with:
          #     dotnet-version: '6.0.x'
          # --- END OF CUSTOM SETUP ---

          echo "Environment setup complete (or skipped)."
          echo "Starting tmate session for interactive access..."

      # Step 3: Start the interactive session using tmate
      # This step will pause the workflow and print connection details in the logs.
      - name: Setup tmate session for Debugging / Interaction
        uses: mxschmitt/action-tmate@v3
        # Optional: You could add a shorter timeout for just this step
        # timeout-minutes: 355 # e.g., 5 mins less than job timeout
        # Optional: Add 'with' block for tmate options if needed
        # with:
        #   sudo: false # sudo is typically not available/needed on Windows runners

      # Step 4: Cleanup message (runs after tmate finishes or job times out)
      # The 'if: always()' ensures this runs even if previous steps fail or are cancelled.
      - name: Session Ended
        if: always()
        shell: pwsh
        run: |
          echo "tmate session ended or job timed out."
